version: '3.3'

services:
  
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./REST_API/my_sql/sql_data/:/var/lib/mysql/
      - ./REST_API/my_sql/sql_conf/:/etc/mysql/conf.d/
      - ./REST_API/my_sql/sql_log/:/var/log/mysql/ 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1008


  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8080:80
  
  
  api:
    build:
      context: ./Dockerfile/
      dockerfile: Dockerfile_mine
    image: php:8.0-apache-xdebug
    container_name: rest
    ports:
      - 81:80
    volumes:
      - ./REST_API/:/var/www/
    tty: true
    stdin_open: true
   
    
  client:
    image: php:8.0-apache-xdebug 
    container_name: app
    ports:
      - 80:80
    volumes:
      - ./UI_for_REST_API/:/var/www/
    tty: true
    stdin_open: true
