products_all:
    path: /products/all
    controller: App\Controller\ProductInStoreController::products_all

product_add:
    path: /product/add
    controller: App\Controller\ProductInStoreController::product_add

product_edit:
    path: /product/edit/{id}
    controller: App\Controller\ProductInStoreController::product_edit

product_delete:
    path: /product/delete/{id}
    controller: App\Controller\ProductInStoreController::product_delete
    




